### ISSUE TITLE
Pasar a Power el PDF juasjuas

### ISSUE THREAD

**Issue by SUPERL00P** [AlbertoFalcon/testing-shits#25]
Psss como es a las 6 lo hago en la tardesita

**Comment by SUPERL00P** [comment]
A nu ma

**Comment by SUPERL00P** [comment]
a la burger

**Comment by AlbertoFalcon** [comment]
Jajajajaj, fue un reto pensar cómo hacer que la cabrona no se respondiera a sí misma.

**Comment by SUPERL00P** [comment]
liton
