### ISSUE TITLE
Does this really work?

### ISSUE THREAD

**Issue by AlbertoFalcon** [AlbertoFalcon/testing-shits#9]
I'd like to know if anyone sees the bot response.
![cyber10](https://user-images.githubusercontent.com/49957900/100417759-39796380-3047-11eb-8e7e-d3a8687fccb1.gif)

**Comment by SUPERL00P** [comment]
Me llego el mensaje Bot

**Comment by SUPERL00P** [comment]
Cerrando el relajo
